# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import e2l_module.__private__.e2ldashboard_pb2 as e2ldashboard__pb2


class GRPCDemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleMethod = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethod',
                request_serializer=e2ldashboard__pb2.Request.SerializeToString,
                response_deserializer=e2ldashboard__pb2.Response.FromString,
                )
        self.ClientStreamingMethod = channel.stream_unary(
                '/e2ldashboard.GRPCDemo/ClientStreamingMethod',
                request_serializer=e2ldashboard__pb2.Request.SerializeToString,
                response_deserializer=e2ldashboard__pb2.Response.FromString,
                )
        self.ServerStreamingMethod = channel.unary_stream(
                '/e2ldashboard.GRPCDemo/ServerStreamingMethod',
                request_serializer=e2ldashboard__pb2.Request.SerializeToString,
                response_deserializer=e2ldashboard__pb2.Response.FromString,
                )
        self.BidirectionalStreamingMethod = channel.stream_stream(
                '/e2ldashboard.GRPCDemo/BidirectionalStreamingMethod',
                request_serializer=e2ldashboard__pb2.Request.SerializeToString,
                response_deserializer=e2ldashboard__pb2.Response.FromString,
                )
        self.SimpleMethodsStatistics = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethodsStatistics',
                request_serializer=e2ldashboard__pb2.SendStatistics.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyStatistics.FromString,
                )
        self.ClientStreamingMethodStatistics = channel.stream_unary(
                '/e2ldashboard.GRPCDemo/ClientStreamingMethodStatistics',
                request_serializer=e2ldashboard__pb2.SendStatistics.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyStatistics.FromString,
                )
        self.ServerStreamingMethodStatistics = channel.unary_stream(
                '/e2ldashboard.GRPCDemo/ServerStreamingMethodStatistics',
                request_serializer=e2ldashboard__pb2.SendStatistics.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyStatistics.FromString,
                )
        self.BidirectionalStreamingMethodStatistics = channel.stream_stream(
                '/e2ldashboard.GRPCDemo/BidirectionalStreamingMethodStatistics',
                request_serializer=e2ldashboard__pb2.SendStatistics.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyStatistics.FromString,
                )
        self.SimpleMethodsLogMessage = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethodsLogMessage',
                request_serializer=e2ldashboard__pb2.SendLogMessage.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyLogMessage.FromString,
                )
        self.SimpleMethodsLogED = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethodsLogED',
                request_serializer=e2ldashboard__pb2.SendLogED.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyLogED.FromString,
                )
        self.SimpleMethodsLogGW = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethodsLogGW',
                request_serializer=e2ldashboard__pb2.SendLogGW.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyLogGW.FromString,
                )
        self.SimpleMethodsLogDM = channel.unary_unary(
                '/e2ldashboard.GRPCDemo/SimpleMethodsLogDM',
                request_serializer=e2ldashboard__pb2.SendLogDM.SerializeToString,
                response_deserializer=e2ldashboard__pb2.ReplyLogDM.FromString,
                )


class GRPCDemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimpleMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingMethod(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStreamingMethod(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleMethodsStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingMethodStatistics(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingMethodStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStreamingMethodStatistics(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleMethodsLogMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleMethodsLogED(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleMethodsLogGW(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleMethodsLogDM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethod,
                    request_deserializer=e2ldashboard__pb2.Request.FromString,
                    response_serializer=e2ldashboard__pb2.Response.SerializeToString,
            ),
            'ClientStreamingMethod': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingMethod,
                    request_deserializer=e2ldashboard__pb2.Request.FromString,
                    response_serializer=e2ldashboard__pb2.Response.SerializeToString,
            ),
            'ServerStreamingMethod': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingMethod,
                    request_deserializer=e2ldashboard__pb2.Request.FromString,
                    response_serializer=e2ldashboard__pb2.Response.SerializeToString,
            ),
            'BidirectionalStreamingMethod': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStreamingMethod,
                    request_deserializer=e2ldashboard__pb2.Request.FromString,
                    response_serializer=e2ldashboard__pb2.Response.SerializeToString,
            ),
            'SimpleMethodsStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethodsStatistics,
                    request_deserializer=e2ldashboard__pb2.SendStatistics.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyStatistics.SerializeToString,
            ),
            'ClientStreamingMethodStatistics': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingMethodStatistics,
                    request_deserializer=e2ldashboard__pb2.SendStatistics.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyStatistics.SerializeToString,
            ),
            'ServerStreamingMethodStatistics': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingMethodStatistics,
                    request_deserializer=e2ldashboard__pb2.SendStatistics.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyStatistics.SerializeToString,
            ),
            'BidirectionalStreamingMethodStatistics': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStreamingMethodStatistics,
                    request_deserializer=e2ldashboard__pb2.SendStatistics.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyStatistics.SerializeToString,
            ),
            'SimpleMethodsLogMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethodsLogMessage,
                    request_deserializer=e2ldashboard__pb2.SendLogMessage.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyLogMessage.SerializeToString,
            ),
            'SimpleMethodsLogED': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethodsLogED,
                    request_deserializer=e2ldashboard__pb2.SendLogED.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyLogED.SerializeToString,
            ),
            'SimpleMethodsLogGW': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethodsLogGW,
                    request_deserializer=e2ldashboard__pb2.SendLogGW.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyLogGW.SerializeToString,
            ),
            'SimpleMethodsLogDM': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleMethodsLogDM,
                    request_deserializer=e2ldashboard__pb2.SendLogDM.FromString,
                    response_serializer=e2ldashboard__pb2.ReplyLogDM.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e2ldashboard.GRPCDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCDemo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimpleMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethod',
            e2ldashboard__pb2.Request.SerializeToString,
            e2ldashboard__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientStreamingMethod(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/e2ldashboard.GRPCDemo/ClientStreamingMethod',
            e2ldashboard__pb2.Request.SerializeToString,
            e2ldashboard__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStreamingMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/e2ldashboard.GRPCDemo/ServerStreamingMethod',
            e2ldashboard__pb2.Request.SerializeToString,
            e2ldashboard__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BidirectionalStreamingMethod(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/e2ldashboard.GRPCDemo/BidirectionalStreamingMethod',
            e2ldashboard__pb2.Request.SerializeToString,
            e2ldashboard__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleMethodsStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethodsStatistics',
            e2ldashboard__pb2.SendStatistics.SerializeToString,
            e2ldashboard__pb2.ReplyStatistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientStreamingMethodStatistics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/e2ldashboard.GRPCDemo/ClientStreamingMethodStatistics',
            e2ldashboard__pb2.SendStatistics.SerializeToString,
            e2ldashboard__pb2.ReplyStatistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStreamingMethodStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/e2ldashboard.GRPCDemo/ServerStreamingMethodStatistics',
            e2ldashboard__pb2.SendStatistics.SerializeToString,
            e2ldashboard__pb2.ReplyStatistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BidirectionalStreamingMethodStatistics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/e2ldashboard.GRPCDemo/BidirectionalStreamingMethodStatistics',
            e2ldashboard__pb2.SendStatistics.SerializeToString,
            e2ldashboard__pb2.ReplyStatistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleMethodsLogMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethodsLogMessage',
            e2ldashboard__pb2.SendLogMessage.SerializeToString,
            e2ldashboard__pb2.ReplyLogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleMethodsLogED(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethodsLogED',
            e2ldashboard__pb2.SendLogED.SerializeToString,
            e2ldashboard__pb2.ReplyLogED.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleMethodsLogGW(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethodsLogGW',
            e2ldashboard__pb2.SendLogGW.SerializeToString,
            e2ldashboard__pb2.ReplyLogGW.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleMethodsLogDM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e2ldashboard.GRPCDemo/SimpleMethodsLogDM',
            e2ldashboard__pb2.SendLogDM.SerializeToString,
            e2ldashboard__pb2.ReplyLogDM.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
