# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import e2gw_rpc_client.edge2gateway_pb2 as edge2gateway__pb2


class Edge2GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handle_ed_pub_info = channel.unary_unary(
                '/edge2gateway.Edge2Gateway/handle_ed_pub_info',
                request_serializer=edge2gateway__pb2.EdPubInfo.SerializeToString,
                response_deserializer=edge2gateway__pb2.GwInfo.FromString,
                )


class Edge2GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handle_ed_pub_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Edge2GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handle_ed_pub_info': grpc.unary_unary_rpc_method_handler(
                    servicer.handle_ed_pub_info,
                    request_deserializer=edge2gateway__pb2.EdPubInfo.FromString,
                    response_serializer=edge2gateway__pb2.GwInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge2gateway.Edge2Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Edge2Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handle_ed_pub_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edge2gateway.Edge2Gateway/handle_ed_pub_info',
            edge2gateway__pb2.EdPubInfo.SerializeToString,
            edge2gateway__pb2.GwInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
