# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge2gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x64ge2gateway.proto\x12\x0c\x65\x64ge2gateway\"W\n\tEdPubInfo\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\x12\x0f\n\x07g_as_ed\x18\x03 \x01(\x0c\x12\x16\n\x0e\x64\x65v_public_key\x18\x04 \x01(\x0c\".\n\x06GwInfo\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x0f\n\x07g_gw_ed\x18\x02 \x01(\x0c\"F\n\x11\x41ggregationParams\x12\x1c\n\x14\x61ggregation_function\x18\x01 \x01(\r\x12\x13\n\x0bwindow_size\x18\x02 \x01(\r\"2\n\nGwResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\rE2LDeviceInfo\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\"\x88\x01\n\x07\x45\x32LData\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x12\x12\x0f\n\x07\x64\x65v_eui\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x03 \x01(\t\x12\x17\n\x0f\x61ggregated_data\x18\x04 \x01(\x12\x12\x1b\n\x13\x61ggregated_data_num\x18\x05 \x01(\x04\x12\x0f\n\x07timetag\x18\x06 \x01(\x04\x32\xf2\x01\n\x0c\x45\x64ge2Gateway\x12\x43\n\x12handle_ed_pub_info\x12\x17.edge2gateway.EdPubInfo\x1a\x14.edge2gateway.GwInfo\x12V\n\x19update_aggregation_params\x12\x1f.edge2gateway.AggregationParams\x1a\x18.edge2gateway.GwResponse\x12\x45\n\x0fremove_e2device\x12\x1b.edge2gateway.E2LDeviceInfo\x1a\x15.edge2gateway.E2LDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge2gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EDPUBINFO']._serialized_start=36
  _globals['_EDPUBINFO']._serialized_end=123
  _globals['_GWINFO']._serialized_start=125
  _globals['_GWINFO']._serialized_end=171
  _globals['_AGGREGATIONPARAMS']._serialized_start=173
  _globals['_AGGREGATIONPARAMS']._serialized_end=243
  _globals['_GWRESPONSE']._serialized_start=245
  _globals['_GWRESPONSE']._serialized_end=295
  _globals['_E2LDEVICEINFO']._serialized_start=297
  _globals['_E2LDEVICEINFO']._serialized_end=347
  _globals['_E2LDATA']._serialized_start=350
  _globals['_E2LDATA']._serialized_end=486
  _globals['_EDGE2GATEWAY']._serialized_start=489
  _globals['_EDGE2GATEWAY']._serialized_end=731
# @@protoc_insertion_point(module_scope)
