# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge2gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x64ge2gateway.proto\x12\x0c\x65\x64ge2gateway\"W\n\tEdPubInfo\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\x12\x0f\n\x07g_as_ed\x18\x03 \x01(\x0c\x12\x16\n\x0e\x64\x65v_public_key\x18\x04 \x01(\x0c\".\n\x06GwInfo\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x0f\n\x07g_gw_ed\x18\x02 \x01(\x0c\x32S\n\x0c\x45\x64ge2Gateway\x12\x43\n\x12handle_ed_pub_info\x12\x17.edge2gateway.EdPubInfo\x1a\x14.edge2gateway.GwInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge2gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EDPUBINFO']._serialized_start=36
  _globals['_EDPUBINFO']._serialized_end=123
  _globals['_GWINFO']._serialized_start=125
  _globals['_GWINFO']._serialized_end=171
  _globals['_EDGE2GATEWAY']._serialized_start=173
  _globals['_EDGE2GATEWAY']._serialized_end=256
# @@protoc_insertion_point(module_scope)
