# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge2gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x64ge2gateway.proto\x12\x0c\x65\x64ge2gateway\"\x1f\n\nActiveFlag\x12\x11\n\tis_active\x18\x01 \x01(\x08\"W\n\tEdPubInfo\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\x12\x0f\n\x07g_as_ed\x18\x03 \x01(\x0c\x12\x16\n\x0e\x64\x65v_public_key\x18\x04 \x01(\x0c\".\n\x06GwInfo\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x0f\n\x07g_gw_ed\x18\x02 \x01(\x0c\"F\n\x11\x41ggregationParams\x12\x1c\n\x14\x61ggregation_function\x18\x01 \x01(\r\x12\x13\n\x0bwindow_size\x18\x02 \x01(\r\"2\n\nGwResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\rE2LDeviceInfo\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\"[\n\x06\x44\x65vice\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x02 \x01(\t\x12\x16\n\x0e\x65\x64ge_s_enc_key\x18\x03 \x01(\x0c\x12\x16\n\x0e\x65\x64ge_s_int_key\x18\x04 \x01(\x0c\"C\n\x16\x45\x32LDevicesInfoComplete\x12)\n\x0b\x64\x65vice_list\x18\x01 \x03(\x0b\x32\x14.edge2gateway.Device\"\x88\x01\n\x07\x45\x32LData\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x12\x12\x0f\n\x07\x64\x65v_eui\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65v_addr\x18\x03 \x01(\t\x12\x17\n\x0f\x61ggregated_data\x18\x04 \x01(\x12\x12\x1b\n\x13\x61ggregated_data_num\x18\x05 \x01(\x04\x12\x0f\n\x07timetag\x18\x06 \x01(\x04\x32\x83\x03\n\x0c\x45\x64ge2Gateway\x12\x43\n\x12handle_ed_pub_info\x12\x17.edge2gateway.EdPubInfo\x1a\x14.edge2gateway.GwInfo\x12V\n\x19update_aggregation_params\x12\x1f.edge2gateway.AggregationParams\x1a\x18.edge2gateway.GwResponse\x12\x45\n\x0fremove_e2device\x12\x1b.edge2gateway.E2LDeviceInfo\x1a\x15.edge2gateway.E2LData\x12M\n\x0b\x61\x64\x64_devices\x12$.edge2gateway.E2LDevicesInfoComplete\x1a\x18.edge2gateway.GwResponse\x12@\n\nset_active\x12\x18.edge2gateway.ActiveFlag\x1a\x18.edge2gateway.GwResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge2gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ACTIVEFLAG']._serialized_start=36
  _globals['_ACTIVEFLAG']._serialized_end=67
  _globals['_EDPUBINFO']._serialized_start=69
  _globals['_EDPUBINFO']._serialized_end=156
  _globals['_GWINFO']._serialized_start=158
  _globals['_GWINFO']._serialized_end=204
  _globals['_AGGREGATIONPARAMS']._serialized_start=206
  _globals['_AGGREGATIONPARAMS']._serialized_end=276
  _globals['_GWRESPONSE']._serialized_start=278
  _globals['_GWRESPONSE']._serialized_end=328
  _globals['_E2LDEVICEINFO']._serialized_start=330
  _globals['_E2LDEVICEINFO']._serialized_end=380
  _globals['_DEVICE']._serialized_start=382
  _globals['_DEVICE']._serialized_end=473
  _globals['_E2LDEVICESINFOCOMPLETE']._serialized_start=475
  _globals['_E2LDEVICESINFOCOMPLETE']._serialized_end=542
  _globals['_E2LDATA']._serialized_start=545
  _globals['_E2LDATA']._serialized_end=681
  _globals['_EDGE2GATEWAY']._serialized_start=684
  _globals['_EDGE2GATEWAY']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
